Parameters:
    ListOfFiles:
      Type: String
      Default: PVP_OHJELMOINTILOMAKE_ASIAKASTARPEET; PVP_OHJELMOINTILOMAKE_HENKILOLIIKENNEPAIKAT; PVP_OHJELMOINTILOMAKE_ISOT_PERUSKORJAUKSET; PVP_OHJELMOINTILOMAKE_KAVALVONTA; PVP_OHJELMOINTILOMAKE_MASTER; PVP_OHJELMOINTILOMAKE_PAALLYSRAKENNETEEMA; PVP_OHJELMOINTILOMAKE_PARANTAMISHANKKEET; PVP_OHJELMOINTILOMAKE_RAPU; PVP_OHJELMOINTILOMAKE_ROPE; PVP_OHJELMOINTILOMAKE_RUMPUTEEMA; PVP_OHJELMOINTILOMAKE_SAHKO; PVP_OHJELMOINTILOMAKE_SILTATEEMA; PVP_OHJELMOINTILOMAKE_TSR_TEEMA; PVP_OHJELMOINTILOMAKE_TUNNELI_KL_TEEMA; PVP_OHJELMOINTILOMAKE_TURVALAITETEEMA; PVP_OHJELMOINTILOMAKE_TURVALLISUUS; PVP_OHJELMOINTILOMAKE_VAIHDETEEMA; PVP_OHJELMOINTILOMAKE_VAK_RP; PVP_OHJELMOINTILOMAKE_YMPARISTO
      Description: List of files to process with lambda. Use semicolon and space to separate filenames without extension.
    LambdaS3Bucket:
      Type: String
      Default: rapido-raportointi-prod
      Description: Lambda code bucket
    LambdaS3Key: 
      Type: String
      Default: excel-to-csv-s3-lambda-1.0.0.jar
      Description: Lambda code file
    LambdaName:
      Type: String
      Default: rapido-excel-to-csv-converter
      Description: Name of the lambda-function
    Administrator:
      Type: String
      Default: arto.lautamo@cgi.com
    Project:
      Type: String
      Default: rapido
    Env:
      Type: String
      Default: dev
      AllowedValues:
        - dev
        - prod
        - test
      Description: Environment where the lambda is deployed

Resources:
    AppLogGroup:
      Type: "AWS::Logs::LogGroup"
      Properties:
        LogGroupName: !Sub "/aws/lambda/${LambdaName}-${Env}"
        Tags:
        - Key: Administrator
          Value: !Ref "Administrator"
  
    IamRoleLambdaExecution:
      Type: "AWS::IAM::Role"
      Properties:
        Path: "/"
        RoleName: !Sub "${LambdaName}-${Env}-role"  
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Principal:
              Service:
              - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
        Policies:
        - PolicyName: !Sub "${LambdaName}-${Env}-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: "Allow"
              Action:
              - "logs:CreateLogStream"
              - "logs:CreateLogGroup"
              - "logs:PutLogEvents"
              Resource:
              - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaName}-${Env}:*"
  
            - Effect: "Allow"
              Action:
              - "s3:*"
              Resource:
              -  !Sub "arn:aws:s3:::rapido-raportointi-${Env}/*"

            - Effect: "Allow"
              Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:ListBucket"
              - "s3:PutObjectAcl"
              - "s3:GetObjectAcl"
              Resource:
              -  !Sub "arn:aws:s3:::vayla-file-load-bucket-${Env}/${Project}_*"
  
        Tags:
        - Key: Administrator
          Value: !Ref "Administrator"
        - Key: Project
          Value: !Ref "Project"

  
    ExcelToCsvLambda:
      Type: "AWS::Lambda::Function"
      Properties:
        Code:
          S3Bucket: !Ref "LambdaS3Bucket"
          S3Key: !Ref "LambdaS3Key"
        Description: "Converts Excel files to CSV"
        FunctionName: !Sub ${LambdaName}-${Env}
        Handler: "com.cgi.lambda.exceltocsv.LambdaFunctionHandler::handleRequest"
        MemorySize: 512
        PackageType: "Zip"
        Role: !GetAtt "IamRoleLambdaExecution.Arn"
        Runtime: "java11"
        Timeout: 120
        Environment:
          Variables:
            add_path_ym: 1
            archive_bucket: !Sub "rapido-raportointi-${Env}"
            archive_path: "archive/"
            first_date: ""
            hasheader: "true"
            last_date: ""
            list_of_files: !Ref "ListOfFiles"
            list_of_files: "PVP_ohjelmointilomake_isot_peruskorjaukset; PVP_ohjelmointilomake_Master_hahmottelua"
            list_of_sheets: "Ohjelmointi"
            master_excel: "PVP_OHJELMOINTILOMAKE_MASTER"
            master_list_of_sheets: Master
            master_skipheaders: 1
            output_bucket: !Sub "vayla-file-load-bucket-${Env}"
            output_path: !Ref "Project"
            output_prefix: !Sub ""
            process_only_listed_files: "true"
            skipheaders: 7


        Tags:
        - Key: Administrator
          Value: !Ref "Administrator"
        - Key: Project
          Value: !Ref "Project"