AWSTemplateFormatVersion: "2010-09-09"
Description: "Velho import secrets to secrets manager"
Parameters:
  VelhoSources:
   Type: String
   Description: List of Velho API sources. Use | to divide addresses. Example http://velho.com/kaide|http://velho.com/bussstop
  VelhoToADEMapping:
   Type: String
   Description: List of mappings if velho has source named kaide and we want data to be in velho_kaide form we add kaide->velho_kaide and if there is multiple mappings they are divided with | like in Velho API source
  VelhoAccesskey:
   Type: String
   NoEcho : "true"
   Description: Access key for Velho API
  VelhoSecretkey:
   Type: String
   Description: Secret key for Velho API
   NoEcho : "true"
Resources: 
    VelhoSecretSources:
       Type: 'AWS::SecretsManager::Secret'
       Properties:
           Name: VelhoSources
           Description: VelhoSources
           SecretString:
             Fn::Sub:
              - "{\"VelhoSources\":\"${VelhoSourcesList}\"}"
              - { VelhoSourcesList : !Ref VelhoSources}
    Velho2ADEMapper:
       Type: 'AWS::SecretsManager::Secret'
       Properties:
           Name: Mapping_velho_source_name_to_ADE
           Description: Velho to ADE mapper
           SecretString:
             Fn::Sub:
              - "{\"VelhoToADEMapping\":\"${VelhoToADEMappingList}\"}"
              - { VelhoToADEMappingList : !Ref VelhoToADEMapping}
    VelhoSecrets:
       Type: 'AWS::SecretsManager::Secret'
       Properties:
           Name: VelhoSecrets
           Description: Storage for Velho API Keys
           SecretString:
             Fn::Sub:
              - "{\"velhoAccessKey\":\"${VelhoAccesskeyV}\",\"velhoSecretKey\":\"${VelhoSecretkeyV}\"}"
              - {VelhoAccesskeyV: !Ref VelhoAccesskey, VelhoSecretkeyV: !Ref VelhoSecretkey }