AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ServiceNowAdeServicesConversion:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::<AWS ACCOUNT NUMBER>:role/servicenowlambda'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: cmdb_ci_service
      Environment:
        Variables:
          destBucket: servicenowadebucket
          destBucketManifest: file-load-ade-runtime-dev
          destBucketManifestPrefix: manifest/servicenow_cmdb_ci_service/
          destBucketManifestProd: file-load-ade-runtime-prod
          srcBucket: servicenowlandingzone2
  Bucket1:
    Type: 'AWS::S3::Bucket'
