AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ServiceNowAPIServicesFetch:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::772136757925:role/servicenowlambda'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 1 * * ? *)
      Environment:
        Variables:
          bucket: servicenowlandingzone2
          bucketKey: cmdb_ci_service.json
          sn_host: liikennevirasto.service-now.com
          sn_passw: password
          sn_path: >-
            /cmdb_ci_service.do?JSONv2&sysparm_query=service_classification=Service&displayvalue=true
          sn_username: username
